FIX Only fetch from next link if it exists

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -92,16 +92,18 @@ runs:
         -H "X-GitHub-Api-Version: 2022-11-28" \
         | sed -n -E 's/link:.*<(.*?)>; rel="next".*/\1/p'
         )
-        # Get the next 100 tags just in case (sometimes needed at the end of a major release line cycle)
-        RESP_CODE=$(curl -w %{http_code} -s -o __tags2.json \
-        -X GET "${NEXT_LINK}" \
-        -H "Accept: application/vnd.github+json" \
-        -H "Authorization: Bearer ${{ github.token }}" \
-        -H "X-GitHub-Api-Version: 2022-11-28" \
-        )
-        if [[ $RESP_CODE != "200" ]]; then
-          echo "Unable to read second page of tags - HTTP response code was $RESP_CODE"
-          exit 1
+        if [[ $NEXT_LINK != "" ]]; then
+          # Get the next 100 tags just in case (sometimes needed at the end of a major release line cycle)
+          RESP_CODE=$(curl -w %{http_code} -s -o __tags2.json \
+          -X GET "${NEXT_LINK}" \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ github.token }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          )
+          if [[ $RESP_CODE != "200" ]]; then
+            echo "Unable to read second page of tags - HTTP response code was $RESP_CODE"
+            exit 1
+          fi
         fi
 
         # Download composer.json for use in branches.php
